<a href="https://colab.research.google.com/github/guenchy/Toti-2026/blob/main/Aula_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aula 4 - NumPy e pandas

## Antes de tudo: dados!

In [ ]:
import pandas as pd

df = pd.read_csv("dados_turma_exemplo.csv")
df

,nome,ano_ingresso,idade,renda_mensal,genero,estado,escolaridade,tem_ctps,nota_final
0,Ana Souza,2023,52,"1.375,15",Mulher cisgênero,Rio de Janeiro,Ensino fundamental completo,Não,7.8
1,Bruno Lima,2024,45,"5.160,29",Homem cisgênero,São Paulo,Superior incompleto,Não,3.7
2,Carla Dias,2023,25,"1.089,12",Mulher cisgênero,Rio de Janeiro,Superior completo,Sim,9.0
3,Diego Alves,2026,19,"1.027,77",Homem cisgênero,São Paulo,NaN,Sim,7.2
4,Eva Nunes,2025,31,"2.636,36",Mulher cisgênero,Rio de Janeiro,Ensino fundamental completo,Não,3.6
5,Felipe Rocha,2023,45,"2.442,92",Homem cisgênero,Rio de Janeiro,Ensino médio completo,Sim,3.9
6,Gabriela Melo,2024,50,"1.015,01",Mulher cisgênero,São Paulo,Superior completo,Sim,6.2
7,Hugo Barros,2023,0,"1.077,19",Homem cisgênero,São Paulo,Ensino médio completo,Não,9.1
8,Isabela Cruz,2024,38,"2.337,54",Mulher cisgênero,Rio de Janeiro,Ensino fundamental completo,Sim,6.4
9,João Pereira,2026,19,"2.693,42",Homem cisgênero,Bahia,Superior incompleto,Sim,4.0
10,Karina Sales,2025,32,"2.087,56",Mulher cisgênero,Minas Gerais,Superior incompleto,Não,4.3
11,Lucas Freitas,2024,49,"2.643,50",Homem cisgênero,São Paulo,NaN,Sim,5.5
12,Marina Costa,2024,33,"2.733,18",Mulher cisgênero,Pernambuco,Ensino médio completo,Sim,8.0
13,Nelson Ramos,2023,43,"4.345,42",Homem cisgênero,São Paulo,Superior completo,Sim,4.2
14,Olívia Tavares,2025,51,"3.200,64",Não-binárie,São Paulo,Superior completo,Não,8.9
15,Paulo Vieira,2024,50,"1.533,21",Homem cisgênero,São Paulo,Ensino fundamental completo,Sim,6.6
16,Queila Martins,2023,23,"1.329,86",Mulher cisgênero,Bahia,Ensino fundamental completo,Sim,5.3
17,Rafael Gomes,2024,52,"2.041,18",Homem cisgênero,Minas Gerais,Superior incompleto,Não,9.9
18,Sofia Correia,2023,52,"2.067,83",Mulher cisgênero,Minas Gerais,Ensino fundamental completo,Não,9.4
19,Tiago Moreira,2025,38,"2.381,80",Homem cisgênero,São Paulo,Superior incompleto,Sim,10.0
20,Úrsula Pinto,2024,23,"1.783,54",Mulher cisgênero,Bahia,Ensino fundamental completo,Não,5.8
21,Victor Andrade,2023,49,"1.353,90",Homem cisgênero,São Paulo,Superior completo,Não,6.0
22,Wanda Teixeira,2025,0,"2.103,85",Mulher cisgênero,São Paulo,Ensino fundamental completo,Não,8.2
23,Xavier Lopes,2023,43,"1.776,80",Homem cisgênero,São Paulo,Ensino fundamental completo,Não,7.4
24,Yasmin Cardoso,2025,49,"2.483,40",Mulher cisgênero,São Paulo,Ensino fundamental completo,Não,4.4
25,Zeca Monteiro,2026,31,"2.026,53",Homem cisgênero,São Paulo,Superior incompleto,Não,9.3
26,Aline Ferraz,2024,39,"1.704,43",Mulher cisgênero,São Paulo,Superior completo,Sim,6.0
27,Bento Aguiar,2023,39,"1.425,77",Homem cisgênero,São Paulo,NaN,Sim,9.7
28,Clara Machado,2025,36,"2.594,60",Mulher cisgênero,Rio de Janeiro,Superior completo,Sim,8.9
29,Davi Rezende,2026,43,"2.352,16",Homem cisgênero,Rio de Janeiro,Superior incompleto,Não,4.0
30,Elisa Fontes,2025,21,"1.170,34",Mulher cisgênero,Rio de Janeiro,Superior incompleto,Não,7.7
31,Fábio Nogueira,2023,20,"2.329,27",Não-binárie,Bahia,Ensino médio completo,Não,5.0
32,Giovana Prado,2023,28,"2.067,94",Mulher cisgênero,Pernambuco,Superior incompleto,Sim,4.8
33,Heitor Bastos,2023,49,"913,93",Homem cisgênero,São Paulo,Superior completo,Sim,5.0
34,Iara Campos,2026,41,"3.605,26",Mulher cisgênero,São Paulo,Ensino médio completo,Sim,4.1
35,Jonas Duarte,2026,0,"1.063,25",Homem cisgênero,Minas Gerais,Ensino fundamental completo,Não,6.5
36,Luana Peixoto,2023,32,"1.241,11",Mulher cisgênero,Pernambuco,Superior completo,Não,7.0
37,Murilo Setúbal,2025,39,"920,60",Homem cisgênero,Bahia,Ensino fundamental completo,Sim,3.7
38,Nara Bittencourt,2023,40,"2.289,68",Mulher cisgênero,Minas Gerais,NaN,Sim,8.8
39,Otávio Queiroz,2024,23,"1.784,38",Homem cisgênero,Bahia,Superior incompleto,Não,4.5

>Até agora, aprendemos a programar. Agora, vamos analisar.

### Aula de hoje: ferramentas

# Mas antes... objetos

In [ ]:
print("  Toti  ".strip)
print([3, 1, 2].count)
print({"a": 1}.keys)

<built-in method strip of str object at 0x7899b3d18630>
<built-in method count of list object at 0x7899cd913500>
<built-in method keys of dict object at 0x7899b3d18d80>

>Funções não existem sozinhas, elas pertencem a uma classe

### Função vs Atributo

**atributo** — informação que ele *tem* — sem parênteses

**método** — ação que ele *faz* — **com** parênteses

In [ ]:
arr.shape
df.head()

# 1. NumPy

> Ele é o pai do Pandas

In [ ]:
# 🎤 As duas bibliotecas do bloco de dados
import numpy as np
import pandas as pd

print("numpy ", np.__version__)
print("pandas", pd.__version__)

numpy  2.0.2
pandas 2.2.2

## 1.1 - Por que usar o NumPy

In [ ]:
# Eu consigo dobrar todas as notas da lista se...
notas = [8.5, 5.0, 9.2]

dobros = []
for nota in notas:
    dobros.append(nota * 2)

print(dobros)

[17.0, 10.0, 18.4]

In [ ]:
# Mas o que eu queria fazer é...
notas = [8.5, 5.0, 9.2]
print(notas * 2)

[8.5, 5.0, 9.2, 8.5, 5.0, 9.2]

## 1.2 - Array e Vetorização

In [ ]:
notas = np.array([8.5, 5.0, 9.2])

In [ ]:
print(notas)

[8.5 5.  9.2]

In [ ]:
print(notas)
print(notas * 2)
print(notas + 1)
print(notas / 10)

[8.5 5.  9.2]
[17.  10.  18.4]
[ 9.5  6.  10.2]
[0.85 0.5  0.92]

> Na vetorização, seus operadores são aplicados a todos os elementos

In [ ]:
# Trabalhando com duas arrays
provas = np.array([8.0, 6.0, 9.0])
trabalhos = np.array([9.0, 7.0, 10.0])

print(provas + trabalhos)
print((provas + trabalhos) / 2)

[17. 13. 19.]
[8.5 6.5 9.5]

### É muito mais rápido!

In [ ]:
import time

n = 1_000_000
lista = list(range(n))
array = np.arange(n)

inicio = time.time()
dobro_lista = []
for x in lista:
    dobro_lista.append(x * 2)
tempo_lista = time.time() - inicio

inicio = time.time()
dobro_array = array * 2
tempo_array = time.time() - inicio

print(f"lista: {tempo_lista:.4f} segundos")
print(f"array: {tempo_array:.4f} segundos")
print(f"o array foi {tempo_lista / tempo_array:.0f}x mais rápido")

lista: 0.2094 segundos
array: 0.0050 segundos
o array foi 42x mais rápido

## 1.3 - Criando arrays

In [ ]:
# 🎤 Os quatro jeitos que você mais vai usar
print(np.array([1, 2, 3, 4, 5]))       # a partir de uma lista
print(np.zeros(5))                     # cinco zeros
print(np.arange(0, 20, 3))                # como o range() de vocês
print(np.linspace(0, 1, 5))            # 5 valores igualmente espaçados entre 0 e 1

[1 2 3 4 5]
[0. 0. 0. 0. 0.]
[ 0  3  6  9 12 15 18]
[0.   0.25 0.5  0.75 1.  ]

>lispace é o inverso de arange

## 1.4 - A forma do Array

In [ ]:
# Uma dimensão
a = np.array([1, 2, 3, 4, 5])

print(a)
print("shape:", a.shape)
print("ndim: ", a.ndim)
print("dtype:", a.dtype)
print("size: ", a.size)

[1 2 3 4 5]
shape: (5,)
ndim:  1
dtype: int64
size:  5

>São atributos ou funções?

In [ ]:
# Duas dimensões — Lembram da lista de listas
b = np.array([
    [8.0, 7.5, 9.0],
    [5.0, 6.0, 4.5],
])

print(b)
print("shape:", b.shape)
print("ndim: ", b.ndim)

[[8.  7.5 9. ]
 [5.  6.  4.5]]
shape: (2, 3)
ndim:  2

In [ ]:
# 🔮 Preveja: qual o dtype de cada um?
print(np.array([1, 2, 3]).dtype)
print(np.array([1.5, 2.5]).dtype)
print(np.array(["a", "b"]).dtype)

int64
float64
<U1

In [ ]:
print(np.array(["a", 1, 1.5]).dtype)
print(np.array(["a", 1, 1.5]))

<U32
['a' '1' '1.5']

## 1.5 Fatiamento

In [ ]:
a = np.array([10, 20, 30, 40, 50])

print(a[0])
print(a[-1])
print(a[1:4])

10
50
[20 30 40]

In [ ]:
b = np.array([
    [8.0, 7.5, 9.0],
    [5.0, 6.0, 4.5],
    [8.0, 7.5, 9.0],
    [5.0, 6.0, 4.5],
    [8.0, 7.5, 9.0],
    [5.0, 6.0, 4.5],
])

print(b[0])
print(b[0, 2])
print(b[:, 0])     # ! Seleciona a primeira coluna de cada linha

[8.  7.5 9. ]
9.0
[8. 5. 8. 5. 8. 5.]

## 1.6 Indexação booleana

In [ ]:
notas = np.array([8.0, 5.5, 9.2, 4.1, 7.0])

print(notas >= 7)

[ True False  True False  True]

In [ ]:
bool_arr = np.array([False, False, True, False, False])

In [ ]:
print(notas[notas >= 7])

[8.  9.2 7. ]

In [ ]:
print("quantos passaram:", notas[notas >= 7].size)

quantos passaram: 3

## 1.7 - Agregações

In [ ]:
notas = np.array([8.0, 5.5, 9.2, 4.1, 7.0])

print("soma: ", notas.sum())
print("média:", notas.mean())
print("maior:", notas.max())
print("menor:", notas.min())
print("desvio:", notas.std())

soma:  33.8
média: 6.76
maior: 9.2
menor: 4.1
desvio: 1.8006665432555802

# 2. Pandas
## 2.1 Do dicionário ao DataFrame

In [ ]:
# Lembram da "tabela" da aula passada
turma = [
    {"nome": "Ana",   "idade": 28, "cidade": "São Paulo",      "nota": 8.5},
    {"nome": "Bruno", "idade": 35, "cidade": "Rio de Janeiro", "nota": 5.0},
    {"nome": "Carla", "idade": 22, "cidade": "São Paulo",      "nota": 9.2},
    {"nome": "Diego", "idade": 41, "cidade": "Salvador",       "nota": 4.1},
    {"nome": "Eva",   "idade": 30, "cidade": "São Paulo",      "nota": 7.0},
]

print(turma[0])
print(turma[0]["nome"])

{'nome': 'Ana', 'idade': 28, 'cidade': 'São Paulo', 'nota': 8.5}
Ana

### Vamos trabalhar com tabelas de verdade!

In [ ]:
df = pd.DataFrame(turma)
df

    nome  idade          cidade  nota
0    Ana     28       São Paulo   8.5
1  Bruno     35  Rio de Janeiro   5.0
2  Carla     22       São Paulo   9.2
3  Diego     41        Salvador   4.1
4    Eva     30       São Paulo   7.0

In [ ]:
print(df)

    nome  idade          cidade  nota
0    Ana     28       São Paulo   8.5
1  Bruno     35  Rio de Janeiro   5.0
2  Carla     22       São Paulo   9.2
3  Diego     41        Salvador   4.1
4    Eva     30       São Paulo   7.0

## 2.2 - Facilidades do Pandas

In [ ]:
# Esse código da aula passada
soma = 0
for aluno in turma:
    soma = soma + aluno["nota"]

print("Média:", soma / len(turma))

Média: 6.76

In [ ]:
# Vira essa linha aqui
df["nota"].mean()

np.float64(6.76)

In [ ]:
# 🎤 O mesmo padrão, várias contas
print("Média:        ", df["nota"].mean())
print("Soma:         ", df["nota"].sum())
print("Maior:        ", df["nota"].max())
print("Menor:        ", df["nota"].min())
print("Quantos:      ", df["nota"].count())
print("Desvio Padrão:", df["nota"].std())

Média:         6.76
Soma:          33.8
Maior:         9.2
Menor:         4.1
Quantos:       5
Desvio Padrão: 2.1915747762739013

# 3. Conhecendo o DataFrame

In [ ]:
df = pd.read_csv("dados_turma_exemplo.csv")

## 3.1 As quatro perguntas

In [ ]:
# 🎤 PERGUNTA 1 — com o que eu estou lidando?
df.head()

,nome,ano_ingresso,idade,renda_mensal,genero,estado,escolaridade,tem_ctps,nota_final
0,Ana Souza,2023,52,"1.375,15",Mulher cisgênero,Rio de Janeiro,Ensino fundamental completo,Não,7.8
1,Bruno Lima,2024,45,"5.160,29",Homem cisgênero,São Paulo,Superior incompleto,Não,3.7
2,Carla Dias,2023,25,"1.089,12",Mulher cisgênero,Rio de Janeiro,Superior completo,Sim,9.0
3,Diego Alves,2026,19,"1.027,77",Homem cisgênero,São Paulo,NaN,Sim,7.2
4,Eva Nunes,2025,31,"2.636,36",Mulher cisgênero,Rio de Janeiro,Ensino fundamental completo,Não,3.6

🗣️ *"`head()` mostra as cinco primeiras. Com 40 mil linhas você não quer ver tudo —
quer ver a cara do dado."* · `df.head(3)` mostra três · `df.tail()` mostra as últimas.

In [ ]:
# 🎤 PERGUNTA 2 — qual o tamanho?
print(df.shape)
print(df.shape[0], "linhas")
print(df.shape[1], "colunas")

(40, 9)
40 linhas
9 colunas

In [ ]:
# 🎤 PERGUNTA 3 — quais colunas, e de que tipo?
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   nome          40 non-null     object
 1   ano_ingresso  40 non-null     int64
 2   idade         40 non-null     int64
 3   renda_mensal  40 non-null     object
 4   genero        40 non-null     object
 5   estado        40 non-null     object
 6   escolaridade  36 non-null     object
 7   tem_ctps      40 non-null     object
 8   nota_final    40 non-null     float64
dtypes: float64(1), int64(2), object(6)
memory usage: 2.9+ KB

- **`RangeIndex: 5 entries`** → quantas linhas
- **`Non-Null Count`** → quantos preenchidos. Menor que o total = **tem dado faltando**
- **`Dtype`** → `int64` e `float64` são números; **`object` é texto**

⚠️ "tem alguma coluna que deveria ser número e está como `object`?"*

In [ ]:
# 🎤 PERGUNTA 4 — como os números se comportam?
df.describe()

       ano_ingresso      idade  nota_final
count     40.000000  40.000000   40.000000
mean    2024.150000  34.800000    6.495000
std        1.098951  14.427893    2.078702
min     2023.000000   0.000000    3.600000
25%     2023.000000  24.500000    4.475000
50%     2024.000000  38.500000    6.300000
75%     2025.000000  46.000000    8.350000
max     2026.000000  52.000000   10.000000

🗣️ *"Só olha as colunas numéricas: contagem, média, desvio, mínimo, máximo e quartis."*

## 3.2 Selecionando colunas

In [ ]:
# Uma coluna
df["nome"]

0            Ana Souza
1           Bruno Lima
2           Carla Dias
3          Diego Alves
4            Eva Nunes
5         Felipe Rocha
6        Gabriela Melo
7          Hugo Barros
8         Isabela Cruz
9         João Pereira
10        Karina Sales
11       Lucas Freitas
12        Marina Costa
13        Nelson Ramos
14      Olívia Tavares
15        Paulo Vieira
16      Queila Martins
17        Rafael Gomes
18       Sofia Correia
19       Tiago Moreira
20        Úrsula Pinto
21      Victor Andrade
22      Wanda Teixeira
23        Xavier Lopes
24      Yasmin Cardoso
25       Zeca Monteiro
26        Aline Ferraz
27        Bento Aguiar
28       Clara Machado
29        Davi Rezende
30        Elisa Fontes
31      Fábio Nogueira
32       Giovana Prado
33       Heitor Bastos
34         Iara Campos
35        Jonas Duarte
36       Luana Peixoto
37      Murilo Setúbal
38    Nara Bittencourt
39      Otávio Queiroz
Name: nome, dtype: object

🗣️ *"Uma coluna sozinha se chama **Series**. É basicamente o array do NumPy com um
índice do lado — por isso `.mean()` funciona nela."*

In [ ]:
# 🔮 Preveja: qual a diferença entre estas duas?
print(type(df["nome"]))
print(type(df[["nome"]]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

⚠️ **Colchete simples devolve Series; colchete duplo devolve DataFrame.**
Com dois colchetes você está passando uma **lista** de colunas.

In [ ]:
# 🎤 Várias colunas: passe uma lista
df[["escolaridade", "nota_final"]].head()

                  escolaridade  nota_final
0  Ensino fundamental completo         7.8
1          Superior incompleto         3.7
2            Superior completo         9.0
3                          NaN         7.2
4  Ensino fundamental completo         3.6

#### Isso é o mais perto que chegamos de:
```sql
SELECT nome, nota FROM turma;
```

In [ ]:
# 🎤 Coluna + método
print(df["estado"].unique())          # SELECT DISTINCT
print()
print(df["estado"].value_counts())    # GROUP BY + COUNT, já ordenado

['Rio de Janeiro' 'São Paulo' 'Bahia' 'Minas Gerais' 'Pernambuco']

estado
São Paulo         18
Rio de Janeiro     8
Bahia              6
Minas Gerais       5
Pernambuco         3
Name: count, dtype: int64

🗣️ **`value_counts()`** é a função mais usada de toda análise exploratória:

```sql
SELECT estado, COUNT(*) FROM turma GROUP BY cidade ORDER BY COUNT(*) DESC;
```

## 3.3 Criando colunas

>Criar colunas que não existem no DataFrame inicial possibilitam análises mais complexas!

In [ ]:
df.head()

,nome,ano_ingresso,idade,renda_mensal,genero,estado,escolaridade,tem_ctps,nota_final
0,Ana Souza,2023,52,"1.375,15",Mulher cisgênero,Rio de Janeiro,Ensino fundamental completo,Não,7.8
1,Bruno Lima,2024,45,"5.160,29",Homem cisgênero,São Paulo,Superior incompleto,Não,3.7
2,Carla Dias,2023,25,"1.089,12",Mulher cisgênero,Rio de Janeiro,Superior completo,Sim,9.0
3,Diego Alves,2026,19,"1.027,77",Homem cisgênero,São Paulo,NaN,Sim,7.2
4,Eva Nunes,2025,31,"2.636,36",Mulher cisgênero,Rio de Janeiro,Ensino fundamental completo,Não,3.6

In [ ]:
df['aprovado'] = df["nota_final"] >= 7

In [ ]:
df.head()

,nome,ano_ingresso,idade,renda_mensal,genero,estado,escolaridade,tem_ctps,nota_final,aprovado
0,Ana Souza,2023,52,"1.375,15",Mulher cisgênero,Rio de Janeiro,Ensino fundamental completo,Não,7.8,True
1,Bruno Lima,2024,45,"5.160,29",Homem cisgênero,São Paulo,Superior incompleto,Não,3.7,False
2,Carla Dias,2023,25,"1.089,12",Mulher cisgênero,Rio de Janeiro,Superior completo,Sim,9.0,True
3,Diego Alves,2026,19,"1.027,77",Homem cisgênero,São Paulo,NaN,Sim,7.2,True
4,Eva Nunes,2025,31,"2.636,36",Mulher cisgênero,Rio de Janeiro,Ensino fundamental completo,Não,3.6,False

In [ ]:
df[["idade", "renda_mensal", "aprovado"]]

    idade renda_mensal  aprovado
0      52     1.375,15      True
1      45     5.160,29     False
2      25     1.089,12      True
3      19     1.027,77      True
4      31     2.636,36     False
5      45     2.442,92     False
6      50     1.015,01     False
7       0     1.077,19      True
8      38     2.337,54     False
9      19     2.693,42     False
10     32     2.087,56     False
11     49     2.643,50     False
12     33     2.733,18      True
13     43     4.345,42     False
14     51     3.200,64      True
15     50     1.533,21     False
16     23     1.329,86     False
17     52     2.041,18      True
18     52     2.067,83      True
19     38     2.381,80      True
20     23     1.783,54     False
21     49     1.353,90     False
22      0     2.103,85      True
23     43     1.776,80      True
24     49     2.483,40     False
25     31     2.026,53      True
26     39     1.704,43     False
27     39     1.425,77      True
28     36     2.594,60      True
29     43     2.352,16     False
30     21     1.170,34      True
31     20     2.329,27     False
32     28     2.067,94     False
33     49       913,93     False
34     41     3.605,26     False
35      0     1.063,25     False
36     32     1.241,11      True
37     39       920,60     False
38     40     2.289,68      True
39     23     1.784,38     False

In [ ]:
cariocas = df["estado"] == "Rio de Janeiro"
df_cariocas = df[cariocas]

aprovados = df_cariocas[df_cariocas["aprovado"]]
aprovados

,nome,ano_ingresso,idade,renda_mensal,genero,estado,escolaridade,tem_ctps,nota_final,aprovado
0,Ana Souza,2023,52,"1.375,15",Mulher cisgênero,Rio de Janeiro,Ensino fundamental completo,Não,7.8,True
2,Carla Dias,2023,25,"1.089,12",Mulher cisgênero,Rio de Janeiro,Superior completo,Sim,9.0,True
28,Clara Machado,2025,36,"2.594,60",Mulher cisgênero,Rio de Janeiro,Superior completo,Sim,8.9,True
30,Elisa Fontes,2025,21,"1.170,34",Mulher cisgênero,Rio de Janeiro,Superior incompleto,Não,7.7,True

In [ ]:
df["nota_ajustada"] = df["nota_final"] * 1.1

In [ ]:
df.head()

,nome,ano_ingresso,idade,renda_mensal,genero,estado,escolaridade,tem_ctps,nota_final,aprovado,nota_ajustada
0,Ana Souza,2023,52,"1.375,15",Mulher cisgênero,Rio de Janeiro,Ensino fundamental completo,Não,7.8,True,8.58
1,Bruno Lima,2024,45,"5.160,29",Homem cisgênero,São Paulo,Superior incompleto,Não,3.7,False,4.07
2,Carla Dias,2023,25,"1.089,12",Mulher cisgênero,Rio de Janeiro,Superior completo,Sim,9.0,True,9.90
3,Diego Alves,2026,19,"1.027,77",Homem cisgênero,São Paulo,NaN,Sim,7.2,True,7.92
4,Eva Nunes,2025,31,"2.636,36",Mulher cisgênero,Rio de Janeiro,Ensino fundamental completo,Não,3.6,False,3.96

# EXTRA - List Comprhension

In [ ]:
numeros = [1, 2, 3, 4, 5]

dobros = []
for n in numeros:
    dobros.append(n * 2)
print(dobros)

[2, 4, 6, 8, 10]

In [ ]:
# Sintaxe
# [<BLOCO_DE_CODIGO> for <PLACEHOLDER> in <LISTA>]

In [ ]:
[n * 2 for n in numeros]

[2, 4, 6, 8, 10]