<a href="https://colab.research.google.com/github/guenchy/Toti-2026/blob/main/Aula_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aula 5 — Limpeza de dados

# Retomada — Quais os problemas desses dados?

In [ ]:
import numpy as np
import pandas as pd

df = pd.read_csv("dados_turma_exemplo.csv")
df.head()

,nome,ano_ingresso,idade,renda_mensal,genero,estado,escolaridade,tem_ctps,nota_final
0,Ana Souza,2023,52,"1.375,15",Mulher cisgênero,Rio de Janeiro,Ensino fundamental completo,Não,7.8
1,Bruno Lima,2024,45,"5.160,29",Homem cisgênero,São Paulo,Superior incompleto,Não,3.7
2,Carla Dias,2023,25,"1.089,12",Mulher cisgênero,Rio de Janeiro,Superior completo,Sim,9.0
3,Diego Alves,2026,19,"1.027,77",Homem cisgênero,São Paulo,NaN,Sim,7.2
4,Eva Nunes,2025,31,"2.636,36",Mulher cisgênero,Rio de Janeiro,Ensino fundamental completo,Não,3.6

## Lembram das 4 perguntas?
>O que?

>Qual o tamanho?

>Quais colunas? Que tipos?

>Como estão os números?

In [ ]:
# O que?
df.tail()

,nome,ano_ingresso,idade,renda_mensal,genero,estado,escolaridade,tem_ctps,nota_final
35,Jonas Duarte,2026,0,"1.063,25",Homem cisgênero,Minas Gerais,Ensino fundamental completo,Não,6.5
36,Luana Peixoto,2023,32,"1.241,11",Mulher cisgênero,Pernambuco,Superior completo,Não,7.0
37,Murilo Setúbal,2025,39,"920,60",Homem cisgênero,Bahia,Ensino fundamental completo,Sim,3.7
38,Nara Bittencourt,2023,40,"2.289,68",Mulher cisgênero,Minas Gerais,NaN,Sim,8.8
39,Otávio Queiroz,2024,23,"1.784,38",Homem cisgênero,Bahia,Superior incompleto,Não,4.5

In [ ]:
# Qual o tamanho?
df.shape

(40, 9)

In [ ]:
# Quais colunas? Que tipos?
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   nome          40 non-null     object
 1   ano_ingresso  40 non-null     int64
 2   idade         40 non-null     int64
 3   renda_mensal  40 non-null     object
 4   genero        40 non-null     object
 5   estado        40 non-null     object
 6   escolaridade  36 non-null     object
 7   tem_ctps      40 non-null     object
 8   nota_final    40 non-null     float64
dtypes: float64(1), int64(2), object(6)
memory usage: 2.9+ KB

In [ ]:
# Como estão os números?
df.describe()

       ano_ingresso      idade  nota_final
count     40.000000  40.000000   40.000000
mean    2024.150000  34.800000    6.495000
std        1.098951  14.427893    2.078702
min     2023.000000   0.000000    3.600000
25%     2023.000000  24.500000    4.475000
50%     2024.000000  38.500000    6.300000
75%     2025.000000  46.000000    8.350000
max     2026.000000  52.000000   10.000000

### Achados
- Renda Mensal está como texto!
- Escolaridade tem informação faltando!
- Tem aluno com idade 0!

# 1. Mas antes

##1.1 Da máscara do NumPy ao filtro do pandas
>Lembram da indexação booleana?

In [ ]:
notas = np.array([8.0, 5.5, 9.2, 4.1, 7.0])

print(notas >= 7)          # array de True/False
print(notas[notas >= 7])   # só os que passaram

[ True False  True False  True]
[8.  9.2 7. ]

In [ ]:
df["nota_final"] >= 7

0      True
1     False
2      True
3      True
4     False
5     False
6     False
7      True
8     False
9     False
10    False
11    False
12     True
13    False
14     True
15    False
16    False
17     True
18     True
19     True
20    False
21    False
22     True
23     True
24    False
25     True
26    False
27     True
28     True
29    False
30     True
31    False
32    False
33    False
34    False
35    False
36     True
37    False
38     True
39    False
Name: nota_final, dtype: bool



```
É a mesmíssima coisa só que no NumPy, era uma Array; no Pandas é um Series
```

In [ ]:
# 🎤 E a máscara filtra o DataFrame inteiro
aprovados = df[df["nota_final"] >= 7]

print(len(aprovados), "aprovados de", len(df))
aprovados.head()

17 aprovados de 40

,nome,ano_ingresso,idade,renda_mensal,genero,estado,escolaridade,tem_ctps,nota_final
0,Ana Souza,2023,52,"1.375,15",Mulher cisgênero,Rio de Janeiro,Ensino fundamental completo,Não,7.8
2,Carla Dias,2023,25,"1.089,12",Mulher cisgênero,Rio de Janeiro,Superior completo,Sim,9.0
3,Diego Alves,2026,19,"1.027,77",Homem cisgênero,São Paulo,NaN,Sim,7.2
7,Hugo Barros,2023,0,"1.077,19",Homem cisgênero,São Paulo,Ensino médio completo,Não,9.1
12,Marina Costa,2024,33,"2.733,18",Mulher cisgênero,Pernambuco,Ensino médio completo,Sim,8.0

## 1.2 Vários critérios

## Como achar alunos do Rio de Janeiro que foram aprovados?

In [ ]:
df_aprovados = df[df["nota_final"] >= 7]
df_aprovados[df_aprovados["estado"] == "Rio de Janeiro"]

,nome,ano_ingresso,idade,renda_mensal,genero,estado,escolaridade,tem_ctps,nota_final
0,Ana Souza,2023,52,"1.375,15",Mulher cisgênero,Rio de Janeiro,Ensino fundamental completo,Não,7.8
2,Carla Dias,2023,25,"1.089,12",Mulher cisgênero,Rio de Janeiro,Superior completo,Sim,9.0
28,Clara Machado,2025,36,"2.594,60",Mulher cisgênero,Rio de Janeiro,Superior completo,Sim,8.9
30,Elisa Fontes,2025,21,"1.170,34",Mulher cisgênero,Rio de Janeiro,Superior incompleto,Não,7.7

In [ ]:
df[(df["nota_final"] >= 7) and (df["estado"] == "Rio de Janeiro")]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

>`and` compara um valor com outro. Se passarmos uma `Series` ele quebra. Pra isso temos o `&`

In [ ]:
rj_aprovados = df[(df["nota_final"] >= 7) & (df["estado"] == "Rio de Janeiro")]

print(len(rj_aprovados), "aprovados no Rio de Janeiro")
rj_aprovados.head()

4 aprovados no Rio de Janeiro

,nome,ano_ingresso,idade,renda_mensal,genero,estado,escolaridade,tem_ctps,nota_final
0,Ana Souza,2023,52,"1.375,15",Mulher cisgênero,Rio de Janeiro,Ensino fundamental completo,Não,7.8
2,Carla Dias,2023,25,"1.089,12",Mulher cisgênero,Rio de Janeiro,Superior completo,Sim,9.0
28,Clara Machado,2025,36,"2.594,60",Mulher cisgênero,Rio de Janeiro,Superior completo,Sim,8.9
30,Elisa Fontes,2025,21,"1.170,34",Mulher cisgênero,Rio de Janeiro,Superior incompleto,Não,7.7

**A regra, escrita na tela:**

| Um valor | Coluna inteira |
|---|---|
| `and` | `&` |
| `or` | `\|` |
| `not` | `~` |

>⚠️ **Os parênteses são obrigatórios.** Sem eles, o `&` tem prioridade sobre o `>=` e o
Python tenta comparar coisas erradas.

In [ ]:
# 🔮 Preveja: quantos alunos têm nota >= 7 OU são de São Paulo?
print(
    len(
        df[(df["nota_final"] >= 7) | (df["estado"] == "São Paulo")]
    )
)

27

## 1.3 Filtrando texto — 8 min

In [ ]:
# 🎤 Lista de valores
print(len(df[df["estado"] == "Bahia"]))
print(len(df[df["estado"].isin(["São Paulo", "Bahia"])]))     # IN do SQL
print(len(df[df["estado"] != "São Paulo"]))

6
24
22

🗣️ **`.isin()` é o `WHERE _ IN` do SQL:**

```sql
SELECT * FROM turma WHERE estado IN ('São Paulo', 'Bahia');
```

In [ ]:
# 🎤 Buscando dentro do texto — o LIKE do SQL
print(df[df["nome"].str.contains("Ana")]["nome"].tolist())
print(df[df["escolaridade"].str.contains("Superior", na=False)].shape[0], "com superior")

['Ana Souza']
19 com superior

#2. Diagnóstico e conversão de tipos

## 2.1 O ritual
>Três exames antes de qualquer análise

In [ ]:
# 🎤 EXAME 1 — tem linha repetida?
print("linhas duplicadas:", df.duplicated().sum())

linhas duplicadas: 0

In [ ]:
# 🎤 EXAME 2 — o que está faltando?
print(df.isna().sum())

nome            0
ano_ingresso    0
idade           0
renda_mensal    0
genero          0
estado          0
escolaridade    4
tem_ctps        0
nota_final      0
dtype: int64

In [ ]:
# 🎤 EXAME 3 — os tipos fazem sentido?
print(df.dtypes)

nome             object
ano_ingresso      int64
idade             int64
renda_mensal     object
genero           object
estado           object
escolaridade     object
tem_ctps         object
nota_final      float64
dtype: object

## 2.2 Achado: `renda_mensal` é object

In [ ]:
df["renda_mensal"].head()

0    1.375,15
1    5.160,29
2    1.089,12
3    1.027,77
4    2.636,36
Name: renda_mensal, dtype: object

Lembram do que a gente tentou na aula passada?

In [ ]:
pd.to_numeric(df["renda_mensal"], errors="coerce")

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
10   NaN
11   NaN
12   NaN
13   NaN
14   NaN
15   NaN
16   NaN
17   NaN
18   NaN
19   NaN
20   NaN
21   NaN
22   NaN
23   NaN
24   NaN
25   NaN
26   NaN
27   NaN
28   NaN
29   NaN
30   NaN
31   NaN
32   NaN
33   NaN
34   NaN
35   NaN
36   NaN
37   NaN
38   NaN
39   NaN
Name: renda_mensal, dtype: float64

## Por quê?
>...

In [ ]:
#  .str.replace
teste = df["renda_mensal"].str.replace(",", ".", regex=False)
print(teste.head())

convertido_errado = pd.to_numeric(teste, errors="coerce")
print("\nconverteram:", convertido_errado.notna().sum(), "de", len(df))

0    1.375.15
1    5.160.29
2    1.089.12
3    1.027.77
4    2.636.36
Name: renda_mensal, dtype: object

converteram: 2 de 40

In [ ]:
# A ordem certa
serie = (df["renda_mensal"]
         .str.replace(".", "", regex=False)     # 1) tira o ponto de MILHAR
         .str.replace(",", ".", regex=False))   # 2) a vírgula decimal vira ponto

print(serie.head())

df["renda"] = pd.to_numeric(serie, errors="coerce")
print("\nconverteram:", df["renda"].notna().sum(), "de", len(df))

0    1375.15
1    5160.29
2    1089.12
3    1027.77
4    2636.36
Name: renda_mensal, dtype: object

converteram: 40 de 40

In [ ]:
df.describe()

       ano_ingresso      idade  nota_final        renda
count     40.000000  40.000000   40.000000    40.000000
mean    2024.150000  34.800000    6.495000  2055.242250
std        1.098951  14.427893    2.078702   916.094853
min     2023.000000   0.000000    3.600000   913.930000
25%     2023.000000  24.500000    4.475000  1347.890000
50%     2024.000000  38.500000    6.300000  2054.505000
75%     2025.000000  46.000000    8.350000  2453.040000
max     2026.000000  52.000000   10.000000  5160.290000

🗣️ **Três coisas para apontar:**

1. **`.str`** — é o acesso aos métodos de texto **da coluna inteira**. `frase.replace()`
   funciona numa string; `coluna.str.replace()` funciona nas quarenta de uma vez.
   É a vetorização de novo.
2. **`regex=False`** — sem isso, o ponto significa "qualquer caractere" e apaga tudo.
   Vale mostrar se sobrar tempo.
3. **Guardei numa coluna nova (`renda`)** em vez de sobrescrever `renda_mensal`.
   Assim dá para conferir depois — e desfazer, se errei.

In [ ]:
# 🎤 errors="coerce" — a decisão escondida nessa linha
print(df["renda"].describe().round(2))

count      40.00
mean     2055.24
std       916.09
min       913.93
25%      1347.89
50%      2054.50
75%      2453.04
max      5160.29
Name: renda, dtype: float64

In [ ]:
df["renda"].isna().sum() # quantos NÃO converteram?

np.int64(0)

## 2.3 Conferindo o resultado

In [ ]:
# FEZ SENTIDO a nossa connversão?
print(df["renda"].dtype)
print(f"menor renda:  R$ {df['renda'].min():>8.2f}")
print(f"maior renda:  R$ {df['renda'].max():>8.2f}")
print(f"média:        R$ {df['renda'].mean():>8.2f}")
print(f"mediana:      R$ {df['renda'].median():>8.2f}")

float64
menor renda:  R$   913.93
maior renda:  R$  5160.29
média:        R$  2055.24
mediana:      R$  2054.51

**Não é porque não deu erro que a conversão deu certo!**

Temos que analisar os dados reais

# Dados faltantes e decisões

## `NaN`

In [ ]:
# 🎤 NaN é o "não sei" do pandas
print(df["escolaridade"].isna().sum(), "sem escolaridade informada")
df[df["escolaridade"].isna()][["nome", "estado", "escolaridade"]]

4 sem escolaridade informada

                nome        estado escolaridade
3        Diego Alves     São Paulo          NaN
11     Lucas Freitas     São Paulo          NaN
27      Bento Aguiar     São Paulo          NaN
38  Nara Bittencourt  Minas Gerais          NaN

### Dados escondidos

In [ ]:
# 🔮 Preveja: quanto dá?
print(np.nan + 10)
print(df["escolaridade"].value_counts())            # ignora os faltantes
print()
print(df["escolaridade"].value_counts(dropna=False))  # mostra os faltantes

nan
escolaridade
Ensino fundamental completo    12
Superior incompleto            10
Superior completo               9
Ensino médio completo           5
Name: count, dtype: int64

escolaridade
Ensino fundamental completo    12
Superior incompleto            10
Superior completo               9
Ensino médio completo           5
NaN                             4
Name: count, dtype: int64

## 3.2 Achado: alunos com `idade == 0`

In [ ]:
# 🎤 Investigar antes de decidir
print("alunos com idade 0:", (df["idade"] == 0).sum())
df[df["idade"] == 0][["nome", "ano_ingresso", "idade", "estado"]]

alunos com idade 0: 3

              nome  ano_ingresso  idade        estado
7      Hugo Barros          2023      0     São Paulo
22  Wanda Teixeira          2025      0     São Paulo
35    Jonas Duarte          2026      0  Minas Gerais

In [ ]:
df["idade"].value_counts()

idade
49    4
23    3
43    3
0     3
52    3
39    3
31    2
19    2
45    2
32    2
38    2
50    2
25    1
51    1
33    1
36    1
21    1
20    1
28    1
41    1
40    1
Name: count, dtype: int64

> É um erro muito comum em bases reais: a pessoa não preenche a informação e o sistema coloca 0 ao invés de vazio

>⚠️ **ATENÇÃO**: zero é um número válido, então entra nas contas.

In [ ]:
# Olhe o que acontece com a nossa média de idade!
print("com os zeros: ", round(df["idade"].mean(), 2))
print("sem os zeros: ", round(df[df["idade"] > 0]["idade"].mean(), 2))

com os zeros:  34.8
sem os zeros:  37.62

# E agora? Precisamos tomar uma decisão!

#### Nossas opções:


| Caminho | Vantagem | Custo |
|---|---|---|
| **Apagar as linhas** | simples, base fica limpa | perde as outras 8 informações dessas 3 pessoas |
| **Trocar 0 por `NaN`** | honesto: "não sabemos" | reduz o `n` das análises de idade |
| **Estimar pela média** | mantém o `n` | inventa dado; distorce a distribuição |

Defendo a decisão: Transformar em `NaN`; `0`, *nesse caso*, é dado vazio

In [ ]:
# DECISÃO: idade 0 significa "não informado". Trocamos por NaN para não
# contaminar as médias. Consequência: as análises de idade usam n=37, não 40.
df["idade"] = df["idade"].astype(float).replace(0, np.nan)

print("média agora:", round(df["idade"].mean(), 2))
print("n de idade: ", int(df["idade"].count()), "de", len(df))
df["idade"].describe().round(2)

média agora: 37.62
n de idade:  37 de 40

count    37.00
mean     37.62
std      10.79
min      19.00
25%      31.00
50%      39.00
75%      49.00
max      52.00
Name: idade, dtype: float64

>⚠️ **ATENÇÃO**: o comentário não é enfeite, é registro de decisão

## 3.3 E se escolhessemos outra opção?
### Ferramentas

In [ ]:
print("dropna: descarta as linhas ->", len(df.dropna(subset=["idade"])), "linhas")
print("fillna: preenche com um valor")
print("  com média:  ", round(df["idade"].fillna(df["idade"].mean()).mean(), 2))
print("  com mediana:", round(df["idade"].fillna(df["idade"].median()).mean(), 2))

dropna: descarta as linhas -> 37 linhas
fillna: preenche com um valor
  com média:   37.62
  com mediana: 37.72

In [ ]:
# 🎤 ⚠️ Mas repare no que preencher faz com a dispersão
col = df["idade"]

comparativo = pd.DataFrame({
    "original":    [col.mean(), col.median(), col.std()],
    "com média":   [col.fillna(col.mean()).mean(),   col.fillna(col.mean()).median(),   col.fillna(col.mean()).std()],
    "com mediana": [col.fillna(col.median()).mean(), col.fillna(col.median()).median(), col.fillna(col.median()).std()],
}, index=["média", "mediana", "desvio padrão"]).round(2)

comparativo

               original  com média  com mediana
média             37.62      37.62        37.72
mediana           39.00      38.50        39.00
desvio padrão     10.79      10.37        10.37

🗣️ *"Preencher faltante com um valor fixo **sempre** reduz a dispersão (desvio padrão) — vocês
inventaram três pessoas exatamente na média, que não variam nada.*

Quando usar:

Média: poucos valores, com pouca variancia

Mediana: tratar outliers, distribuição torta

NaN: muitos valores vazios; > 20%

### Se for coluna categórica, podemos criar uma categoria:

In [ ]:
df["escolaridade"].value_counts()

escolaridade
Ensino fundamental completo    12
Superior incompleto            10
Superior completo               9
Ensino médio completo           5
Name: count, dtype: int64

In [ ]:
# Coluna categórica
df["escolaridade"] = df["escolaridade"].fillna("Não informado")
df["escolaridade"].value_counts()

escolaridade
Ensino fundamental completo    12
Superior incompleto            10
Superior completo               9
Ensino médio completo           5
Não informado                   4
Name: count, dtype: int64

#`groupby`

In [ ]:
# O que a gente já conhece
df["estado"].value_counts()

estado
São Paulo         18
Rio de Janeiro     8
Bahia              6
Minas Gerais       5
Pernambuco         3
Name: count, dtype: int64

### O problema: isso retorna uma `Series`

In [ ]:
df.groupby("estado") # parecido com df

In [ ]:
df.groupby("estado")["renda"].mean().round(2).sort_values(ascending=False) # podemos manipular mais informações

estado
São Paulo         2209.93
Pernambuco        2014.08
Rio de Janeiro    1999.77
Minas Gerais      1909.90
Bahia             1806.84
Name: renda, dtype: float64

In [ ]:
# Várias contas de uma vez!
resumo = df.groupby("estado").agg(
    alunos=("nome", "size"),
    renda_media=("renda", "mean"),
    nota_media=("nota_final", "mean"),
).round(2).sort_values("alunos", ascending=False)

resumo

                alunos  renda_media  nota_media
estado
São Paulo           18      2209.93        6.75
Rio de Janeiro       8      1999.77        6.41
Bahia                6      1806.84        4.72
Minas Gerais         5      1909.90        7.78
Pernambuco           3      2014.08        6.60

# Salvar a base limpa!

In [ ]:
df.to_csv("dados_turma_limpo.csv", index=False)

print("Salvo:", df.shape[0], "linhas x", df.shape[1], "colunas")
print("Colunas criadas hoje:", [c for c in ["renda"] if c in df.columns])
print()
df.head(3)

Salvo: 40 linhas x 10 colunas
Colunas criadas hoje: ['renda']

,nome,ano_ingresso,idade,renda_mensal,genero,estado,escolaridade,tem_ctps,nota_final,renda
0,Ana Souza,2023,52.0,"1.375,15",Mulher cisgênero,Rio de Janeiro,Ensino fundamental completo,Não,7.8,1375.15
1,Bruno Lima,2024,45.0,"5.160,29",Homem cisgênero,São Paulo,Superior incompleto,Não,3.7,5160.29
2,Carla Dias,2023,25.0,"1.089,12",Mulher cisgênero,Rio de Janeiro,Superior completo,Sim,9.0,1089.12

*"`index=False` evita salvar aquela coluna de números da esquerda. Sem isso, toda vez que vocês salvarem e reabrirem, nasce uma coluna de lixo."*